Repository pesca-dev/moneyboy-app, pull requests merged in 2021-08, with the labels that each got.

#4 Add `README.md`
  README.md
Labels: documentation, enhancement

#7 Update package name to `moneyboy-app`
  package-lock.json
  package.json
Labels: enhancement

#19 Update ESLint and lint the project in CI
  .eslintignore
  .github/workflows/build.yml
  package-lock.json
  package.json
Labels: enhancement, ci-cd

#21 Add Fastlane manifests and build workflows for iOS and Android
  .github/workflows/android.yml
  .github/workflows/ios.yml
  Gemfile
  Gemfile.lock
  README.md
  android/fastlane/.gitignore
  android/fastlane/Appfile
  android/fastlane/Fastfile
  ios/fastlane/.gitignore
  ios/fastlane/Appfile
  ios/fastlane/Fastfile
Labels: enhancement, ci-cd, ios

#26 Fix: Downgrade TypeScript Version to 4.2
  package-lock.json
  package.json
Labels: bug, app

#1 Feature: single payments UI
  babel.config.js
  index.js
  ios/Podfile
  ios/Podfile.lock
  package-lock.json
  package.json
  src/api/PescaClient.ts
  src/api/PescaNavContextType.ts
  src/api/ThemeType.d.ts
  src/components/extended/AddPaymentButton.tsx
  src/components/extended/CenterButton.tsx
  src/components/extended/GroupListItem.tsx
  src/components/extended/LogoutButton.tsx
  src/components/extended/MoneyDiff.tsx
  src/components/extended/addPaymentButton/ConfirmPaymentView.tsx
  src/components/extended/addPaymentButton/EnterPaymentView.tsx
  src/components/extended/addPaymentButton/SearchListView.tsx
  src/components/input/PescaAmountField.tsx
  src/components/input/PescaButton.tsx
  src/components/input/PescaInputField.tsx
  src/components/navigation/PescaTabBar.tsx
  src/components/navigation/PescaTabIcon.tsx
  src/components/navigation/pesca-navigator/createPescaNavigation.tsx
  src/components/navigation/pesca-navigator/pescaNavigator.tsx
  src/components/navigation/pesca-navigator/pescaScreen.tsx
  src/components/structure/Flyout.tsx
  src/components/structure/Footer.tsx
  src/components/structure/ListItem.tsx
  src/components/structure/ViewBase.tsx
  src/context/AuthContext.tsx
  src/context/FlyoutContext.tsx
  src/context/PescaContext.tsx
  src/context/ThemeContext.tsx
  src/global.d.ts
  src/pesca/createPescaClient.ts
  src/util/amountUtil.ts
  src/views/AppContainer.tsx
  src/views/pages/GroupView.tsx
  src/views/pages/HistoryView.tsx
  src/views/pages/LoginView.tsx
  src/views/pages/MainView.tsx
  src/views/pages/RegisterView.tsx
  src/views/pages/SettingsView.tsx
  tsconfig.json
Labels: enhancement, app

#31 Generate Xcode project using Xcodegen
  .github/workflows/ios.yml
  .gitignore
  ios/MoneyBoy.xcodeproj/project.pbxproj
  ios/MoneyBoy.xcodeproj/xcshareddata/xcschemes/MoneyBoy.xcscheme
  ios/Podfile
  ios/Podfile.lock
  ios/project.yml
  scripts/setup-ios
Labels: enhancement, ios

#39 Fastlane TestFlight Support
  .github/workflows/testflight.yml
  .gitignore
  ios/MoneyBoy/logo.png
  ios/fastlane/Appfile
  ios/fastlane/Fastfile
  ios/fastlane/Matchfile
  ios/project.yml
Labels: ci-cd, ios, app

#41 Fix overflow of SectionList in SearchListView
  README.md
  assets/screenshot_enter_amount.png
  assets/screenshot_main.png
  assets/screenshot_search_user.png
  src/components/extended/addPaymentButton/SearchListView.tsx
  src/components/navigation/pesca-navigator/pescaNavigator.tsx
  src/components/structure/Flyout.tsx
Labels: bug, app

#42 Fix: Keyboard in Confirmation View
  src/components/extended/addPaymentButton/EnterPaymentView.tsx
Labels: bug, app

#44 Feature: Add date selection to enter payment view
  ios/Podfile.lock
  package-lock.json
  package.json
  src/components/extended/addPaymentButton/ConfirmPaymentView.tsx
  src/components/extended/addPaymentButton/EnterPaymentView.tsx
Labels: enhancement, app

#49 Feature: bubbled center button
  src/api/PescaMenuContextType.d.ts
  src/components/extended/AddPaymentButton.tsx
  src/components/extended/CenterButton.tsx
  src/components/extended/pescaMenu/createPescaMenu.tsx
  src/components/extended/pescaMenu/menuItem.tsx
  src/components/extended/pescaMenu/pescaMenu.tsx
Labels: enhancement, app
